### ISSUE TITLE
雨课堂

### ISSUE THREAD

**Issue by hismyth** [Fly-MZX/RainClassroom-Assistant#1]
请问雨课堂脚本还会开放吗

**Comment by Fly-Playgroud** [comment]
可能会考虑重新写js脚本，不过目前项目已经有新的软件版本了。推荐使用软件版本。另外，如果考虑移动端的话，后续也可能推出安卓版本。请你关注本项目的进度。

**Comment by hankaize55** [comment]
这个软件版本就下exe就可以了吗？我没找到怎么打开雨课堂。
